### ISSUE TITLE
Wrong requirements

### ISSUE THREAD

**Issue by trivago-makbarof** [fightbulc/simplon_mysql#17]
I can see in the latest versions you are using php7 typings.
In your composer.json you're still mentioning 5.4 which causes problem if I run composer update with php 5.4

**Comment by duduindo** [comment]
True, @trivago-makbarof <br><br> ` ): ?string` :-1:   <br> `): ?array` :-1:

**Comment by fightbulc** [comment]
@trivago-makbarof thanks for the catch. `composer.json` has been fixed.

@duduindo sure, if you dont run php 7+ you can stay with the version 1.
